package io.github.sfkamath.jvmhotpath.it;

import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.stream.Stream;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

@Timeout(value = 2, unit = TimeUnit.MINUTES)
class MainClassResolutionMicronautIT {

  private static final String MODULE_SELECTOR = "integration-tests-micronaut";
  private static final String PROBE_MAIN_CLASS =
      "io.github.sfkamath.jvmhotpath.sample.micronaut.MainClassProbe";
  private static final String SKIP_INSTALL_PROPERTY = "jvmhotpath.it.skipPluginInstall";
  private static final Duration COMMAND_TIMEOUT = Duration.ofSeconds(60);
  private static final Path MODULE_ROOT = Path.of("").toAbsolutePath().normalize();
  private static final Path REPO_ROOT = MODULE_ROOT.getParent().normalize();
  private static final Path REPORT_DIR =
      REPO_ROOT.resolve(MODULE_SELECTOR).resolve("target/site/jvm-hotpath");
  private static final Path REPORT_HTML = REPORT_DIR.resolve("execution-report.html");

  @BeforeAll
  static void installLatestPluginArtifacts() throws Exception {
    if (Boolean.parseBoolean(System.getProperty(SKIP_INSTALL_PROPERTY, "false"))) {
      System.out.println(
          "[MainClassResolutionMicronautIT] skipping plugin install ("
              + SKIP_INSTALL_PROPERTY
              + ")");
      return;
    }

    ProcessResult installResult =
        runCommand(
            List.of(
                "mvn",
                "-pl",
                "agent,maven-plugin",
                "-am",
                "install",
                "-DskipTests",
                "-Dskip.frontend=true",
                "-Dmaven.install.skip=false",
                "-Dmaven.deploy.skip=true"),
            REPO_ROOT,
            Duration.ofMinutes(5));

    assertEquals(
        0,
        installResult.exitCode,
        "Expected plugin install to succeed before matrix execution.\n" + installResult.output);
  }

  @BeforeEach
  void cleanReportArtifacts() throws IOException {
    if (!Files.exists(REPORT_DIR)) {
      return;
    }
    try (Stream<Path> walker = Files.walk(REPORT_DIR)) {
      walker.sorted(Comparator.reverseOrder()).forEach(this::deleteQuietly);
    }
  }

  @Test
  void shouldUseMainClassConfiguredInPomByDefault() throws Exception {
    System.out.println("[MainClassResolutionMicronautIT] case=default-pom-mainClass");
    ProcessResult result = runPrepareAgentAndExec(List.of());

    assertEquals(0, result.exitCode, result.output);
    assertTrue(result.output.contains("Inferred exec.mainClass: " + PROBE_MAIN_CLASS), result.output);
    assertTrue(Files.exists(REPORT_HTML), "Expected report at " + REPORT_HTML);
  }

  @Test
  void shouldFailFastWhenMainClassIsUnsetAndNoFallbackIsProvided() throws Exception {
    System.out.println("[MainClassResolutionMicronautIT] case=unset-mainClass-no-fallback");
    ProcessResult result = runPrepareAgentAndExec(List.of("-Djvm-hotpath.mainClass="));

    assertNotEquals(0, result.exitCode, result.output);
    assertTrue(
        result.output.contains("Could not determine exec.mainClass for exec:exec"),
        result.output);
    assertFalse(
        result.output.contains("Report written to:"),
        "No report should be generated by the fail-fast command.\n" + result.output);
  }

  @ParameterizedTest(name = "{index} => {0}")
  @MethodSource("resolutionCases")
  void shouldResolveMainClassFromSupportedSources(
      String caseName, List<String> extraArgs, boolean expectInference) throws Exception {
    System.out.println("[MainClassResolutionMicronautIT] case=" + caseName);
    ProcessResult result = runPrepareAgentAndExec(extraArgs);

    assertEquals(0, result.exitCode, "Case failed: " + caseName + "\n" + result.output);
    if (expectInference) {
      assertTrue(
          result.output.contains("Inferred exec.mainClass: " + PROBE_MAIN_CLASS),
          "Expected inference log for case " + caseName + "\n" + result.output);
    } else {
      assertFalse(
          result.output.contains("Inferred exec.mainClass:"),
          "Did not expect inference log for case " + caseName + "\n" + result.output);
    }
    assertTrue(Files.exists(REPORT_HTML), "Expected report at " + REPORT_HTML);
  }

  private static Stream<org.junit.jupiter.params.provider.Arguments> resolutionCases() {
    return Stream.of(
        org.junit.jupiter.params.provider.Arguments.of(
            "exec.mainClass", List.of("-Djvm-hotpath.mainClass=", "-Dexec.mainClass=" + PROBE_MAIN_CLASS), false),
        org.junit.jupiter.params.provider.Arguments.of(
            "jvm-hotpath.mainClass", List.of("-Djvm-hotpath.mainClass=" + PROBE_MAIN_CLASS), true),
        org.junit.jupiter.params.provider.Arguments.of(
            "main.class", List.of("-Djvm-hotpath.mainClass=", "-Dmain.class=" + PROBE_MAIN_CLASS), true),
        org.junit.jupiter.params.provider.Arguments.of(
            "mainClass", List.of("-Djvm-hotpath.mainClass=", "-DmainClass=" + PROBE_MAIN_CLASS), true),
        org.junit.jupiter.params.provider.Arguments.of(
            "start-class", List.of("-Djvm-hotpath.mainClass=", "-Dstart-class=" + PROBE_MAIN_CLASS), true),
        org.junit.jupiter.params.provider.Arguments.of(
            "spring-boot.run.main-class",
            List.of("-Djvm-hotpath.mainClass=", "-Dspring-boot.run.main-class=" + PROBE_MAIN_CLASS),
            true));
  }

  private static ProcessResult runPrepareAgentAndExec(List<String> extraArgs) throws Exception {
    List<String> command =
        new ArrayList<>(
            List.of(
                "mvn",
                "-pl",
                MODULE_SELECTOR,
                "-DskipTests",
                "-Djvm-hotpath.flushInterval=0",
                "jvm-hotpath:prepare-agent",
                "org.codehaus.mojo:exec-maven-plugin:3.5.0:exec",
                "-Dexec.executable=java",
                "-Dexec.args=${argLine} -classpath %classpath ${exec.mainClass}"));
    command.addAll(extraArgs);

    return runCommand(command, REPO_ROOT, COMMAND_TIMEOUT);
  }

  private static ProcessResult runCommand(List<String> command, Path workingDir, Duration timeout)
      throws IOException, InterruptedException, ExecutionException, TimeoutException {
    ProcessBuilder processBuilder = new ProcessBuilder(command);
    processBuilder.directory(workingDir.toFile());
    processBuilder.redirectErrorStream(true);

    Process process = processBuilder.start();
    ExecutorService pool = Executors.newSingleThreadExecutor();
    Future<String> outputFuture =
        pool.submit(
            () -> {
              try (InputStream input = process.getInputStream();
                  ByteArrayOutputStream buffer = new ByteArrayOutputStream()) {
                input.transferTo(buffer);
                return buffer.toString(StandardCharsets.UTF_8);
              }
            });

    try {
      boolean completed = process.waitFor(timeout.toMillis(), TimeUnit.MILLISECONDS);
      if (!completed) {
        process.destroyForcibly();
        String partial = safeOutput(outputFuture);
        return new ProcessResult(-1, partial + "\nProcess timed out after " + timeout + ".");
      }
      String output = outputFuture.get(10, TimeUnit.SECONDS);
      return new ProcessResult(process.exitValue(), output);
    } finally {
      pool.shutdownNow();
    }
  }

  private static String safeOutput(Future<String> future) {
    try {
      return future.get(2, TimeUnit.SECONDS);
    } catch (Exception ignored) {
      return "";
    }
  }

  private void deleteQuietly(Path path) {
    try {
      Files.deleteIfExists(path);
    } catch (IOException ignored) {
      // Best-effort cleanup for test artifacts.
    }
  }

  private static final class ProcessResult {
    private final int exitCode;
    private final String output;

    private ProcessResult(int exitCode, String output) {
      this.exitCode = exitCode;
      this.output = output == null ? "" : output;
    }
  }
}
